services:
  - type: web
    name: propelai01
    env: python
    buildCommand: pip install -r requirements-prod.txt && npm install -g docx
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
